title: "&6도전과제 — %tab%"

nav:
  all:    { slot: 0, material: BOOKSHELF,     name: "&e전체", custom-model-data: 0 }
  daily:  { slot: 1, material: SUNFLOWER,     name: "&6일일", custom-model-data: 0 }
  weekly: { slot: 2, material: CLOCK,         name: "&b주간", custom-model-data: 0 }
  season: { slot: 3, material: NETHER_STAR,   name: "&d시즌", custom-model-data: 0 }


list_slots: [9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53]

item:
  in_progress: { material: WHITE_STAINED_GLASS_PANE, custom-model-data: 0 }
  completed:   { material: LIME_STAINED_GLASS_PANE,  custom-model-data: 0 }

  name: "%title%"
  lore:
    - "&7진행: &a%value%&7/&f%target% &8(%percent%%)"
    - "&7보상:"
    - "%rewards%"     # 여기에서 보상 목록이 줄 단위로 펼쳐짐(명령은 OP에게만 표시)
    - "{op}&8키: %key%"  # {op} 프리픽스가 있으면 OP에게만 보임
