events:
  progress_add: { sound: ENTITY_EXPERIENCE_ORB_PICKUP, volume: 1.0, pitch: 1.6 }
  completed:    { sound: UI_TOAST_CHALLENGE_COMPLETE,  volume: 1.0, pitch: 1.0 }
  claimed:      { sound: BLOCK_NOTE_BLOCK_BELL,        volume: 1.0, pitch: 1.0 }
  cooldown:     { sound: BLOCK_NOTE_BLOCK_BASS,        volume: 1.0, pitch: 0.6 }
  error:        { sound: ENTITY_VILLAGER_NO,           volume: 1.0, pitch: 1.0 }
