general:
  timezone: "Asia/Seoul"        # 리셋/시즌 스케줄 기준 시간대
  storage: yaml                  # yaml | sqlite | mysql (현재 v0.1.x는 yaml만 동작)
  apply_async: true              # 내부 저장 비동기 처리

feedback:
  actionbar: true                # 진행시 액션바 안내
  bossbar: false                 # 보스바 안내(미사용 자리)
  # 개별 사운드는 config/sounds.yml에서 설정 (여기 값은 무시됨)

scoreboard:
  enabled: true
  title: "&6도전과제"
  # ※ 스코어보드는 v0.1.x에선 표시 로직만 자리 잡아둔 상태

anti_cheese:
  placed_block_exclude_default: true   # 설치블록 제외
  repeat_coord_decay_radius: 5         # 같은 좌표 파밍 감쇠 반경(블록)
  rate_cap:
    default:
      per_5s: 50
      per_60s: 500
  min_samples_for_full_reward: 15

auto_claim_rewards: false        # 완료 시 자동 수령 여부(현재는 수동 수령 권장)

reset_schedules:
  daily_hour: 0                  # 매일 00:00 리셋
  weekly_day: MONDAY             # 매주 월요일 리셋
  weekly_hour: 0
