name: Advancement
main: org.haemin.advancement.AdvancementPlugin
version: 1.0.0
api-version: '1.20'
softdepend: [Vault, PlaceholderAPI, WorldGuard, MythicMobs, ItemsAdder, MMOItems]
commands:
  adv:
    aliases: [도전과제, advancement, challenges]
    description: Open GUI
    permission: advancement.user
permissions:
  advancement.user:
    default: true
  advancement.admin:
    default: op
