name: Auto-merge Codex PRs
on:
  pull_request:
    types: [opened, synchronize, labeled]
permissions:
  contents: write
  pull-requests: write

jobs:
  enable-automerge:
    if: >
      github.event.pull_request.head.ref != null &&
      (startsWith(github.event.pull_request.head.ref, 'codex/')
       || contains(github.event.pull_request.title, '[codex]'))
    runs-on: ubuntu-latest
    steps:
      - name: Enable native auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash
